services:
  app:
    build: .
    depends_on:
      - database
      - database-csv
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/postgres
      - DATABASE_URL_CSV=postgresql://postgres:postgres@database-csv:5432/postgres
    volumes:
      - .:/app

  database:
    image: "postgres:15"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - database-data-15:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - 5432:5432
  database-csv:
    image: "postgres:15"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - database-data-csv-15:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - 5434:5432

volumes:
  database-data-15: # named volumes can be managed easier using docker-compose
  database-data-csv-15: # named volumes can be managed easier using docker-compose
